cksource/mrgit

lib/commands/update.js
=> Checking out to specific commit (hash) works as it should.

lib/commands/bootstrap.js, lib/commands/exec.js, lib/commands/savehashes.js, lib/commands/update.js, lib/index.js, lib/utils/log.js, package.json, tests/commands/bootstrap.js, tests/commands/exec.js, tests/commands/savehashes.js, tests/commands/update.js, tests/fixtures/project-a/package.json, tests/fixtures/project-with-options-in-mgitjson/package.json
Fix: Fixed various minor issues with the commands. Introduced missing tests. Closes #31. Closes #41. Closes #3. Closes #43.
=> T/43: Added tests

lib/commands/savehashes.js, tests/commands/savehashes.js
Other: Shortened hashes to 7-char version in `savehashes` command. Closes #47.
=> Provide 7-char hashes in savehashes command

lib/commands/status.js, tests/commands/status.js
Other: Improved UI of the displayed table with statuses with repositories. Closes #55.
* If current branch is other than specified in `mgit.json` – the branch will be prefixed with `!`,
* If current branch is other than `master` – the whole row will be highlighted (in pink).
=> T/55: Mgit status should highlight all non-master rows

lib/commands/status.js, tests/commands/status.js
Fix: Packages displayed in a table (`mgit status`) will be sorted in order by alphabetical. Closes #60.
=> Packages will be sorted in order by alphabetical

lib/utils/gitstatusparser.js, tests/utils/gitstatusparser.js
Fix: Not staged, deleted files were not shown as modified during `mgit status` command. Closes #58.
=> T/58: Status command failed to read status of repo in which files were removed

lib/commands/bootstrap.js, tests/commands/bootstrap.js
Fix: A space in a path will not break the bootstrap command. Closes #74.
Wrapped every path in quotation marks because they can contain a space that will break the command. 
---
It works.
=> Space in path will not break the bootstrap command

.travis.yml, README.md
Internal: Removed CodeClimate integration. Introduced Coveralls.io instead. Closes #70.
=> Coveralls.io instead of CodeClimate

lib/index.js, lib/utils/displaylog.js
Fix: Mgit should end with proper exit code if some command failed. Closes #86.
=> Mgit should end with proper exit code if some command failed

lib/commands/bootstrap.js, package.json, tests/commands/bootstrap.js
Feature: Introduced a mechanism which allows executing `bootstrap` command once again if it ends with an error. Closes #87.
=> Bootstrap command will retry itself if failed

lib/commands/bootstrap.js, tests/commands/bootstrap.js
Fix: Simplified a check for "remote end hung up" error during the `bootstrap` command. Closes #92.
=> Simplified the error check

lib/index.js
Fix: The master repository package should not be loaded to packages dir. Closes #96.
---
* Happy testing
=> Exclude master repo package from requiring.

lib/utils/parserepositoryurl.js, tests/utils/parserepositoryurl.js
Feature: Allows cloning packages using the `file://` protocol. Closes #101.
=> enable cloning from file urls (e.g. file:///workspace/myrepo/.git)

lib/commands/status.js, lib/default-resolver.js, lib/utils/getoptions.js, tests/commands/status.js, tests/default-resolver.js, tests/fixtures/project-a/mgit.json, tests/utils/getoptions.js
Feature: Introduced an option (`overrideDirectoryNames`) that allows modifying a directory where a package would be cloned. Closes #72.
=> Introduced the "overrideDirectoryNames" option in a config

README.md, lib/default-resolver.js, lib/utils/getoptions.js, lib/utils/parserepositoryurl.js, tests/utils/getoptions.js, tests/utils/parserepositoryurl.js
Feature: Support for standard/core branches. Closes #103.
=> Support for standard/core branches

lib/commands/status.js, tests/commands/status.js
Fix: Number of unmerged files will be shown as "modified" in the table while execution the `status` command. Closes #107.
=> Unmerged files will be counted as modified during "mgit status"

README.md, package.json, scripts/bump-version.js, scripts/publish.js, yarn.lock
Internal: Adjusted release scripts to a new version of `@ckeditor/ckeditor5-dev-env`.
---
Requires: https://github.com/ckeditor/ckeditor5-dev/pull/497
=> Adjusted release scripts to a new version of ckeditor5-dev-env

lib/index.js
Feature: Repositories, where an executed command failed, will be printed out at the end of the mgit log. Closes #104.
---
=> Print out repositories where an executed command failed

README.md
Doc: Fix link to config object definition in README
Let me know if i should amend the commit message to follow the convention (using the above text), i just used the github ui.
Type: Message. Closes #000.
=> Update README.md - Fix link to config object definition

.editorconfig, .gitignore, README.md, index.js, lib/commands/close.js, lib/commands/commit.js, lib/commands/exec.js, lib/commands/pull.js, lib/commands/push.js, lib/commands/save.js, lib/commands/status.js, lib/commands/sync.js, lib/utils/gitstatusparser.js, lib/utils/log.js, lib/utils/parserepositoryurl.js, package.json, tests/commands/close.js, tests/commands/commit.js, tests/commands/pull.js, tests/commands/push.js, tests/commands/save.js, tests/commands/status.js, tests/commands/sync.js, tests/default-resolver.js, tests/fixtures/project-a/mrgit.json, tests/utils/gitstatusparser.js, tests/utils/parserepositoryurl.js, yarn.lock
Feature: Added support for tags. Closes #148.
---
*For example – encountered issues, assumptions you had to make, other affected tickets, etc.*
=> Added support for tags

README.md, index.js, lib/commands/save.js, lib/commands/status.js, lib/utils/getoptions.js, tests/commands/save.js, tests/commands/status.js, tests/fixtures/project-with-presets/mrgit.json, tests/utils/getoptions.js
Feature: Added support for presets. Closes #151.
Fix: Fixed message displayed by the `status` command when using specific commit defined in the config file.
=> Added support for presets

lib/commands/status.js, lib/commands/sync.js, lib/utils/log.js, tests/commands/status.js, tests/commands/sync.js, tests/utils/log.js
Fix: The `status` and `sync` commands will no longer fail when a repository has no tag. Closes #157.
=> Fixed errors caused by repositories without tags

README.md, index.js, lib/commands/close.js, lib/commands/diff.js, lib/commands/exec.js, lib/commands/fetch.js, lib/commands/pull.js, lib/commands/push.js, lib/commands/save.js, lib/commands/status.js, lib/commands/sync.js, lib/default-resolver.js, lib/index.js, lib/utils/getcommandinstance.js, lib/utils/getoptions.js, lib/utils/getpackagenames.js, lib/utils/rootrepositoryutils.js, package.json, tests/commands/status.js, tests/default-resolver.js, tests/fixtures/project-with-defined-root/mrgit.json, tests/utils/getoptions.js, tests/utils/getpackagenames.js, yarn.lock
Feature: Added support for executing commands in the root repository. Closes #160.
---
*For example – encountered issues, assumptions you had to make, other affected tickets, etc.*
=> Implemented root repository feature

lib/commands/status.js, tests/commands/status.js
Fix: The `mrgit status` command should not print an error when processing a repository without tags or with a partially cloned history that causes tags to be assigned to non-existing commits. Closes #179.
---
*For example – encountered issues, assumptions you had to make, other affected tickets, etc.*
=> Added fallback for when there is no tag
